
version: '3.8'
networks: 
  reso:
    driver: bridge
services:
  app:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - reso
  java:
    build: ./iapau-analytics/.
    ports:
      - "8081:8081"
    networks:
      - reso
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=iapau
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iapau
    ports:
      - "5432:5432"
    networks:
      - reso